### ISSUE TITLE
Can't get this to run

### ISSUE THREAD

**Issue by adamtyoung** [harvard-dce/canvas-docker#12]
Seems like there is a very verbose Gems error that is preventing the database from starting? A line:

`PG::ConnectionBad: FATAL:  the database system is starting up`

**Comment by adamtyoung** [comment]
Still seems like Postgres takes about an hour to start up. This message:

`UTC FATAL:the database system is starting up`

**Comment by lbjay** [comment]
Hey, sorry I didn't get to this sooner. Can you clarify you're seeing this error during `docker run...`? Or are you trying to build the image? If it's a container run, could you paste the full `docker logs` output?

**Comment by adamtyoung** [comment]
Hi,
  I am not sure what changed, but it is running fine now. Thanks!
