### ISSUE TITLE
Wrong admin's password in dockerhub documentation 

### ISSUE THREAD

**Issue by AlxGolubev** [harvard-dce/canvas-docker#15]
I've noticed that your documentation in docker hub contains the wrong password, it's `canvas` in docker hub 
![image](https://user-images.githubusercontent.com/2353443/34523824-19c0a646-f0aa-11e7-88bb-846fffade335.png)

while in the repo's readme it's presented with `canvas-docker`
![image](https://user-images.githubusercontent.com/2353443/34523834-23b6b550-f0aa-11e7-912b-b2b2913570da.png)

I didn't find the way how I can fix that for you, so I decided to create an issue.

https://hub.docker.com/r/lbjay/canvas-docker/

**Comment by lbjay** [comment]
Oh hey! Thanks for pointing that out. I guess I assumed the docker hub entry would somehow update itself, but the readme there was very much out of date and seems to require a manual update. All set now.

**Comment by AlxGolubev** [comment]
@lbjay many thanks!
