### ISSUE TITLE
Automatic user registration emails don't work.

### ISSUE THREAD

**Issue by pfgray** [harvard-dce/canvas-docker#7]
Hi there!
I've pulled and run the latest version of canvas-docker from the docker hub, and I noticed that automatic emails don't get sent. This poses a problem when I try to create a new user, as I can't initiate a user with a password (they must confirm their email address by clicking on the link in the email they never received).

The stacktrace I found in the logs is:

```
Exception: SocketError: getaddrinfo: Name or service not known
...
/usr/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
/opt/canvas-lms/vendor/bundle/ruby/2.1.0/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/opt/canvas-lms/vendor/bundle/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:2129:in `do_delivery'
/opt/canvas-lms/vendor/bundle/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:232:in `block in deliver'
...
script/delayed_job:10:in `<main>'
```

It looks like the stacktrace is pointing to: https://github.com/instructure/canvas-lms/blob/stable/app/models/message.rb#L690

It looks like canvas uses this ruby gem to send emails: https://github.com/mikel/mail and according to the [docs](https://github.com/mikel/mail#sending-an-email), it defaults to a local smtp server.

I'm not sure if canvas makes this configurable or not (could be verified by someone at instructure), but this could probably be resolved by adding http://www.postfix.org/ to the docker  container setup process.

**Comment by lbjay** [comment]
Can you elaborate on why you're creating users? I'm guessing it's part of testing some process or workflow, but just want to confirm. I never intended this to be a full featured instance that would be used for anything more than testing/dev. Is there perhaps some way to construct the necessary confirmation url manually by looking in the database?

**Comment by pfgray** [comment]
I'm testing an LTI application in canvas, so I was creating a few users that I could use to test launches (a few students & one instructor).

With any integration testing, it's handy to have a docker image that you can stand up to test against locally.

I was able to inspect the logs to obtain the special registration url that users need (since canvas logs the html sent out in emails), but I don't want to have to go through those steps anytime I want to create a new user.

**Comment by djcp** [comment]
You can configure your SMTP settings in `$CANVAS_ROOT/config/outgoing_mail.yml`, according to the canvas defaults. Adding another service to this docker image seems a bit much. 

You can probably just set "delivery_method" to "test" for every environment. I'm pretty sure that means it'll only send outgoing emails to the logs.

**Comment by lbjay** [comment]
So the image doesn't yet have any hooks for modifying `outgoing_mail.yml`, but that's something I could add through an ENTRYPOINT script. You would then be able to specify your smtp service via one or more env vars. Something like Mailgun or Mandrill would be a good fit.

**Comment by djcp** [comment]
right, maybe give all environments a default of:

```
development: 
    delivery_method: test

test: 
    delivery_method: test

production: 
    delivery_method: test
```

and then add the hook to configure beyond that. This'll at least keep actions that send emails from erroring out.

**Comment by lbjay** [comment]
Paul, can you take a look at https://github.com/harvard-dce/canvas-docker/pull/9 and confirm that would solve your use case?

**Comment by pfgray** [comment]
It would, the only issue I have is that I'd need a separate smtp service running, which seems like too much overhead. My use case is basically: "Get a (low-frills) instance of canvas running with the least amount of keystrokes possible."

If you think that it's too much to add postfix, don't feel that you have to support my use case, I simply thought I'd make it work for me and contribute something back in the process (though I'm not sure what would be 'bad' about running another service).

Thanks for your help!

**Comment by lbjay** [comment]
Hi Paul,

I appreciate the effort. It's true that the image does already break the convention of 1-container:1-service by including postgres and redis, but those are pretty much essential to standing up a functional instance in as short amount of time as possible. I'd prefer to keep the image bloat minimized if alternatives are available. Mandrill, for instance, is free for < 1250 msg/month. It's a one-time setup and you can use it for whatever other purposes you might also have. You can even put those extra vars in a file and reference using `docker run --env-file=...` to save keystrokes at runtime.

It's a good use case that I'll probably run across myself at some point, so thanks for the prompting.
